# build front-end
FROM node:lts-alpine AS frontend

RUN npm install pnpm -g

WORKDIR /app

COPY ./package.json /app

COPY ./pnpm-lock.yaml /app

RUN pnpm install

COPY . /app

RUN pnpm run build


# service
FROM python:3.10-alpine

LABEL Author=wuyuw515@gmail.com

RUN mkdir /opt/chatgptapi
COPY /chatgptapi /opt/chatgptapi

WORKDIR /opt/chatgptapi

COPY --from=frontend /app/dist/ /opt/chatgptapi/static

RUN pip install -r requirements.txt

RUN mv /opt/chatgptapi/demo.env /opt/chatgptapi/.env

EXPOSE 3002

# ENTRYPOINT ["python", "-m", "gunicorn", "wsgi:app", "-b", "0.0.0.0:3002"]
CMD ["python", "-m", "gunicorn", "wsgi:app", "-b", "0.0.0.0:3002"]
